# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e8c5afd376ab6107c4764078cefb394c5a3f8c7e7c2f573d589de4e567a9d803d11786008f48d0e8df07d8e7ef6e7b98888c4544285fdba28cf91c028ce6920

test:
  secret_key_base: 74d7a44b7400c95e5b8b21fc3196bbf7d3beced3519d3ff0509df76d6a7069a5bd34f116d4b428934963401c2957e6c39698c6da74d2ca832f9c5c299370c3ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
